### PR TITLE
Fixes #77 - PoseidonTree root hash count is fixed

### LINKED ISSUE #77: Perform fixed amount of hashes to calculate the root

### PR DESCRIPTION
**Pull request by vlopes11**

### CODE REVIEW

File: src/tree/mod.rs [hunk 1]
```diff
@@ -101,14 +101,11 @@ where
...
-            io::Error::new(
-                io::ErrorKind::Other,
-                "Kelvin shouldn't fail at reading annotations",
-            )
-        })?;
-        let storage_scalar: &StorageScalar = first_level.borrow();
-        Ok(storage_scalar.to_owned().into())
+        let branch = self
+            .poseidon_branch(0)?
+            .unwrap_or(PoseidonBranch::mock(&[], self.branch_depth as usize));
```
Comment (CPerezz) [inline src/tree/mod.rs:106]: I don't think this is the expected behaviour of the function. 

If `self.poseidon_branch` failed, there's no reason at all to return something that is completely mocked. Since it simply does not represent anything related to the real tree/branch.

**Review by CPerezz — CHANGES_REQUESTED** [review]
LGTM, just that Result nit that I would like to check if follows the expected behaviour.

File: src/tree/mod.rs (hunk 1 above)
Comment (vlopes11) [reply src/tree/mod.rs:106]: That unwrap is not for failing, but for being non-existent. In this case, its a `None`, not an `Err`. If the tree don't contain any elements, it will be `None`

**Review by CPerezz — APPROVED** [review]
LGTM.

Good job!
