### PR TITLE
Adding fixed hash length

### LINKED ISSUE #51: Implement Poseidon Hashing variant with two outputs and fixed WIDTH
After talking to @khovratovich  we will need to implement a new Poseidon module inside of the Poseidon repo which takes different values from the Permutation.

The reason for that is that Luke_Pearson needs to get two inputs from a Poseidon hash, and with the current implementation of the sponge_hash it is not possible.

This is blocking the eddsa impl (See: https://github.com/dusk-network/eddsa/pull/1 ) and therefore @khovratovich is working on the docs in Gitbook.
We'll start coding the solution (which will not be tricky) as soon as the docs are done.

### PR DESCRIPTION
**Pull request by LukePearson1**
This PR adds a function which allows us to take in one BlsScalar and output 2. This is for use in the EdDSA scheme for JubJub. 
This closes #51.

### CODE REVIEW

**Review by CPerezz — CHANGES_REQUESTED** [review]
The impl has nothing to do with the specs mentioned in https://app.gitbook.com/@dusk-network/s/specs/specifications/poseidon/poseidon-usages/

Please, check fixed-len hashing section. 
I can go through it with you if you want.

File: src/sponge/pad.rs [hunk 1]
```diff
@@ -35,6 +35,26 @@ where
...
+    // For a constant length hash, we always use a slice of width 5.
+    let width = 5;
+    let zero = pad_value;
+    let mut words = vec![zero; width];
+
+    words[0] = capacity;
+    words[1] = message;
+    words
+}
+
```
Comment (CPerezz) [inline src/sponge/pad.rs]: This pad should not be inside the sponge module. 
Please move it under the same module where the fixed hash file lives.

File: src/perm_uses/fixed_hash.rs [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+    }
+
+    #[test]
+    fn same_result() {
+        let m = BlsScalar::random(&mut rand::thread_rng()); 
+        
+        let h = two_outputs(m); 
+        let h_1 = two_outputs(m);
+        
+        assert_eq!(h, h_1);
```
Comment (CPerezz) [inline src/perm_uses/fixed_hash.rs]: Could you wrap this inside of a loop that does the operation 100 times or so? On that way we are sure that it doesn't fail.

File: src/perm_uses/fixed_hash.rs [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+        vec![BlsScalar::zero(); WIDTH],
+        |mut inputs, values| {
+            let mut values = values.iter();
+            inputs
+                .iter_mut()
+                .for_each(|input| *input += values.next().unwrap());
+            strategy.perm(&mut inputs);
+            inputs
+        },
+    );
```
Comment (CPerezz) [inline src/perm_uses/fixed_hash.rs]: Why do you need to do any of these things?

You already know that the inputs are as max: WIDTH - 1. Therefore it makes no sense that you have here code copied from the sponge that doesn't have anything to do and that will add functionalities that you don't want.

File: src/perm_uses/fixed_hash.rs [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+/// Takes in one BlsScalar and outputs 2. 
+/// This function is fixed.
+pub fn two_outputs(message: BlsScalar) -> [BlsScalar; 2] {
+    let mut strategy = ScalarStrategy::new();
+
+    // The value used to pad the words is zero.
+    let padder = BlsScalar::zero();
+
+    // The capacity is 
+    let capacity = BlsScalar::one() * BlsScalar::from(2<<64-1) + BlsScalar::one();
```
Comment (CPerezz) [inline src/perm_uses/fixed_hash.rs]: This could be a constant.

File: src/sponge/pad.rs [hunk 5]
```diff
@@ -35,6 +35,26 @@ where
...
+    message: T,
+    pad_value: T,
+) -> Vec<T>
+where
+    T: Clone,
+{
+    // For a constant length hash, we always use a slice of width 5.
+    let width = 5;
+    let zero = pad_value;
+    let mut words = vec![zero; width];
```
Comment (CPerezz) [inline src/sponge/pad.rs]: As I said, would not be difficult to turn that into a generic function for any number of inputs/outputs < WIDTH.

Anyway, for the time being maybe that's fine. Even I encourage you to try it.

**Review by CPerezz — CHANGES_REQUESTED** [review]

File: src/perm_uses/fixed_hash.rs (hunk 4 above)
Comment (LukePearson1) [reply src/perm_uses/fixed_hash.rs]: I don't want to encode it as a constant for now, incase we opt for the change in number of inputs and outputs.

File: src/sponge/pad.rs (hunk 5 above)
Comment (LukePearson1) [reply src/sponge/pad.rs]: I would like to do this in the future when it is optimised for circuits.

File: src/perm_uses/fixed_hash.rs (hunk 3 above)
Comment (LukePearson1) [reply src/perm_uses/fixed_hash.rs]: I have refactored this for use with fixed width.

File: src/perm_uses/fixed_hash.rs (hunk 4 above)
Comment (CPerezz) [reply src/perm_uses/fixed_hash.rs]: Is there any reason why not? It will be faster and cleaner. The only reason to have that is if you were doing a generic impl over the ammount of inputs/outputs

File: src/sponge/pad.rs (hunk 5 above)
Comment (CPerezz) [reply src/sponge/pad.rs]: Doesn't have anything to do with circuits but ok

File: src/perm_uses/fixed_hash.rs (hunk 4 above)
Comment (LukePearson1) [reply src/perm_uses/fixed_hash.rs]: Because if the use case of the fixed hash is going to become something other EdDSA, then we cannot have capacity as constant. Linked to the comment below, if we have an in circuit use, in the future, of a fixed hash then both a generic function and varying `capacity` will be needed.

File: src/sponge/pad.rs (hunk 5 above)
Comment (LukePearson1) [reply src/sponge/pad.rs]: See above comment for my train of thought

**Review by CPerezz — APPROVED** [review]
LGTM
